# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2

include:
  - local: .gitlab/ci/templates.gitlab-ci.yml
  - local: .gitlab/ci/pre.gitlab-ci.yml
  - local: .gitlab/ci/build-app.gitlab-ci.yml
  - local: .gitlab/ci/download-secrets.gitlab-ci.yml
  - local: .gitlab/ci/lint.gitlab-ci.yml
  - local: .gitlab/ci/unit-tests.gitlab-ci.yml
  - local: .gitlab/ci/sign-release.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml
#  - local: .gitlab/ci/upload.gitlab-ci.yml
  - local: .gitlab/ci/release.gitlab-ci.yml
  - local: .gitlab/ci/update-version.gitlab-ci.yml
  - local: .gitlab/ci/license-check.gitlab-ci.yml
  - local: .gitlab/ci/security.gitlab-ci.yml
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - .pre
  - license-check
  - download-secrets
  - build
  - test
  - sign
  - deploy
  - release

