include:
  - local: .gitlab/ci/templates.gitlab-ci.yml
  - local: .gitlab/ci/pre.gitlab-ci.yml
  - local: .gitlab/ci/build-app.gitlab-ci.yml
  - local: .gitlab/ci/lint.gitlab-ci.yml
  - local: .gitlab/ci/unit-tests.gitlab-ci.yml
#  - local: .gitlab/ci/sign-release.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml
  - local: .gitlab/ci/upload.gitlab-ci.yml
  - local: .gitlab/ci/release.gitlab-ci.yml
  - local: .gitlab/ci/update-version.gitlab-ci.yml
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - .pre
  - build
  - test
  - sign
  - deploy
  - release

