version = 1

[[annotations]]
path = "app/src/main/res/font/dm*.ttf"
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2014 The DM Sans Project Authors (https://github.com/googlefonts/dm-fonts)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "app/src/main/res/font/bricolage*.ttf"
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2022 The Bricolage Grotesque Project Authors (https://github.com/ateliertriay/bricolage)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
    "README.md",
    "NOTICES.md",
]
precedence = "override"
SPDX-FileCopyrightText = "2025. FairPhone B.V."
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = [
    "Gemfile*",
    "fastlane/*"
]
precedence = "override"
SPDX-FileCopyrightText = "MIT License"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "gradle*",
    "gradle/wrapper/*",
    "config/licenses/allowed-licenses.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Apache License 2.0"
SPDX-License-Identifier = "Apache-2.0"


