# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2


download:google-services:
  extends: .secure-files-download-job
  stage: download-secrets
  variables:
    SECURE_FILE_ID: 15
    SECURE_FILE_PATH: app/google-services.json
  artifacts:
    paths:
      - app/google-services.json
    expire_in: 1 hour