# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2


download:google-services:
  extends:
    - .secure-files-download-job
    - .rule:if-no-version-upgrade-requested
  stage: download-secrets
  variables:
    SECURE_FILE_ID: 15
    SECURE_FILE_PATH: app/google-services.json
  artifacts:
    paths:
      - app/google-services.json
    expire_in: 1 hour

download:keystore:
  extends:
    - .secure-files-download-job
    - .rule:if-no-version-upgrade-requested
  stage: download-secrets
  variables:
    SECURE_FILE_ID: 9
    SECURE_FILE_PATH: spring_launcher_release_key.jks
  artifacts:
    paths:
      - spring_launcher_release_key.jks
    expire_in: 1 hour