# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2

lint:debug:
  extends:
    - .gradle-android-job
  interruptible: true
  stage: test
  needs:
    - job: download:google-services
      artifacts: true
  script:
    - ./gradlew lintDebug -PbuildDir=lint

lint:release:
  extends:
    - .gradle-android-job
    - .release-rule
  interruptible: true
  stage: test
  needs:
    - job: download:google-services
      artifacts: true
  script:
    - ./gradlew lintRelease -PbuildDir=lint
