# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2

create-release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - !reference [.release-rule, rules]
  needs:
    - job: deploy:release:apk:gitlab-registry
      artifacts: true
  script:
    - echo "Running job $CI_JOB_NAME for tag $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: Release $CI_COMMIT_TAG
    assets:
      links:
        - name: $FILENAME
          url: $ARTIFACT_URL
