# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2

sast:
  extends:
    - .rule:if-no-version-upgrade-requested
  stage: test
  artifacts:
    reports:
      sast: gl-sast-report.json

#owasp:dependency:security:check:
#  extends:
#    - .gradle-android-job
#    - .rule:if-no-version-upgrade-requested
#  stage: test
#  script:
#    - ./gradlew dependencyCheckUpdate dependencyCheckAnalyze
