# Copyright (C) 2025 FairPhone B.V.
#
# SPDX-FileCopyrightText: 2025. FairPhone B.V.
#
# SPDX-License-Identifier: EUPL-1.2

include:
  - local: .gitlab/ci/templates/gradle-android-job.gitlab-ci.yml
  - local: .gitlab/ci/templates/rules.gitlab-ci.yml
  - local: .gitlab/ci/templates/secure-files-download-job.gitlab-ci.yml
